### ISSUE TITLE
「JSONのパースに失敗しました。：html.json」と表示されてスニペット登録に失敗します

### ISSUE THREAD

**Issue by satoshiss** [fiore57/snippet-generator#7]
Snippet GeneratorをWindowsのVScodeで使用したいと思い設定していますが、スニペットを登録しようとすると「JSONのパースに失敗しました。：html.json」と表示されて登録に失敗します。
setting.jsonに "generateSnippet.snippetFilePath": "C:\\Users\\ユーザー名\\Appdata\\Roaming\\Code\\User\\snippets\\"　を追記済みです。
（「"generateSnippet.snippetFilePath": "/mnt/c/Users/ユーザ名/Appdata/Roaming/Code/User/snippets"だとスニペットの登録に失敗しました。 "setting.json" の "generateSnippet.snippetFilePath" を確認してください」と表示されます）
なぜかわかりますでしょうか。
当方jsonの記述に詳しくないので何か記述の間違えという可能性もあるかもしれません。
何かわかることがあればご回答頂けますと幸いです。

**Comment by fiore57** [comment]
まず、https://lab.syncer.jp/Tool/JSON-Viewer/ などのJSON構文チェックツールで、`html.json` の中身を確認してみてください。

特に問題ないようであれば、`html.json` の中に
```json
{
  "For Loop": {
    "prefix": ["for", "for-const"],
    "body": ["for (const ${2:element} of ${1:array}) {", "\t$0", "}"],
    "description": "A for loop."
  }
}
```
のように、prefix が複数存在するスニペットがあるかどうかを確認してください。

そのようなスニペットが存在しない場合は、`html.json` の中身を貼りつけてください。

よろしくお願いします。

**Comment by satoshiss** [comment]
構文チェックでエラーが出たのでhtml.jsonの記述に問題があるようです。
表示されたエラーメッセージで調べてみます。
ありがとうございます！
